### ISSUE TITLE
Anglicized Sanskrit Coding Scheme

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/SCH#1]
As stated in the readme file: The general AS scheme, described in CDSL.pdf, is:
x1 = macron
x2 = dot below
x3 = dot above
x4 = accent aigu
x5 = tilde
x6 = dash below
x7 = umlaut
x10 = circonflex (hat)
x11 = accent grave

In this case x is stands for a vowel (if we speak about macrons) and about consonants (if dot below). So in real life conditions it will be:
s2 = ṣ
a4 = á
u4 = ú
o4 = ó
h2 = ḥ
i4 = í
m2 = ṃ
t2 = ṭ

What is not documented, that there can be combinations:
a14 = ā́
a18=a,ā (no unicode point)
r24 = ṛ́

To find it out I need to search for sample words. #viSTyakarNI3# is a sample word in HK. It contains I3, something I want to understand. But at http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/disp2/index.php it can't be found. So I look for #viSTikarmakara#, the word before it and that way I can find http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/disp2/sch_serveimg.php?filepfx=334 and see, that I3 = ī́. A long journey, but the result is good. I propose the pwg-meta.txt file should contain all the possible combinations in UTF-8, and not in cp1252 encoding.
If I would follow the 
x3 = dot above
x4 = accent aigu
logic, than #viSTyakarNI3# should be #viSTyakarNI4#, but is not.

**Comment by drdhaval2785** [comment]
Now everything is in IAST. Closing.
