### ISSUE TITLE
BHĀGAVATAPURĀṆA SCH literary source markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/SCH#10]
Standardization of the literary source markup in sch dictionary, for  BhP.

**Comment by funderburkjim** [comment]
## work finished.
See [issue10 directory](https://github.com/sanskrit-lexicon/SCH/tree/master/schissues/issue10).

Compared to PWG, PW, MW the SCH digitization has minimal markup.
An example of literary sources reference markup:
```
BEFORE current work
 <ls>Suśr.</ls> 1, 27, 14. — 2. sanft, milde (Augen), <ls>Bhāg. P.</ls> 3, 13, 28. 
AFTER
<ls>Suśr. 1,27,14.</ls> — 2. sanft, milde (Augen), <ls>Bhāg. P. 3,13,28.</ls>
```
Such changes were made in the change function of link_prepare.py. Note
these were 'global'.

After this preparation, a small number of changes specific to 'Bhāg. P. ' were made -- see change_2.txt file.

There were also revisions to the basicadjust.php component of the display code to 'activate' the parameterized links to 'Bhāg. P. ' 

Incidentally, although the burnouf link target covers only skandhas 1-9,
the display program still links to burnouf for skandhas 10-12;  if we develop a link target for the 'Bombay' edition, then the display code will need corresponding adjustment.

Closing this issue as completed.

**Comment by Andhrabharati** [comment]
@funderburkjim ,

I suggest that you should carry the same correction in SCH [L-3837] as at pwkvn [L-6319], for the 'apravizwa' entry.

**Comment by funderburkjim** [comment]
> SCH [L-3837] as at pwkvn [L-6319], 

Done. Also another print change detected and changed.
Also fixed deficiency in basicadjust for the sch link targets.
See the readme file (version 3), and the commits above.
