### ISSUE TITLE
SCH-Nachträge

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/SCH#2]
Marcis, Can you provide an html version of SCH-Nachtrage?
An html version could be readily incorporated into Sanskrt-Lexicon Documentation.

I looked at https://www.youtube.com/watch?v=UMX-JEsmcyk&feature=youtu.be  in which you describe how you use Acrobat, Abby Finereader, and MSWord to get text out of scanned documents.

Probably MSWord has an 'export to html' function that will do the conversion.

**Comment by drdhaval2785** [comment]
@gasyoun It is closable from Jim's point of view. 
Do you have anything pending here?
