### ISSUE TITLE
[Schµ793] €1

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/SCH#3]
When searching for "aja" in http://www.sanskrit-lexicon.uni-koeln.de/scans/SCHScan/2014/web/webtc/indexcaller.php I get "m. = *Kāma , Yudh. 1 , 80. [Schµ793] €1" - [Schµ793]  is something I'm not sure I want to see in web display and €1 is a rather cheap price, but for what? And could we get mnf at least in some different color (it's not italics in the book) with RegEx, so at least some structure would be reflected, please?

**Comment by drdhaval2785** [comment]
Now the digitization is as follows.
```
<L>774<pc>011-2<k1>aja<k2>aja
{#aja#} {%aja%}¦  m. = *Kāma , Yudh. 1 , 80. {part=,seq=793,type=,n=1}
<LEND>
```
Euro sign is gone now. Closing.
